import { demolitionChallenge, parseDemolitionProgress } from "../../../shared/game/demolitionChallenges";
type LaneState={targets:number;goal:number;time:number;completed:boolean;garage:boolean};
export class DemolitionDuel {
 private frames:HTMLIFrameElement[]=[];private states:(LaneState|null)[]=[null,null];private running=false;
 private root!:HTMLElement;private challenge=0;
 private round=0;
 start(){
  document.body.classList.add("duel-page");this.root=document.querySelector<HTMLElement>("#hud-root")!;this.root.className="demo-duel";document.querySelector("#game-root")!.replaceChildren();
  let unlocked=0;try{unlocked=parseDemolitionProgress(localStorage.getItem("lobbers-demolition-progress")).unlocked;}catch{/* Optional persistence. */}
  this.root.innerHTML=`<header class="duel-header"><div><h1>DOUBLE TROUBLE.</h1><p>Same puzzle. Two inventions. First to topple every target wins.</p></div><div><a href="/">← Solo ladder</a><select id="duelChallenge" aria-label="Duel challenge">${Array.from({length:Math.min(unlocked+1,10000)},(_,i)=>`<option value="${i}">${i+1}. ${demolitionChallenge(i).name}</option>`).join("")}</select><button id="duelStart" disabled>Loading machines…</button></div></header><div class="duel-readout"><span id="duelBlue">TEAL · build your machine</span><strong id="duelStatus" role="status">Build separately, then start together.</strong><span id="duelRed">CORAL · build your machine</span></div><main class="duel-lanes"><section><h2>TEAL <small>A/D · Space hop · J hammer · Shift boost · W water</small></h2><div id="duelLane1"></div></section><section><h2>CORAL <small>←/→ · ↑ hop · Enter hammer · ↓ boost · / water</small></h2><div id="duelLane2"></div></section></main><p class="duel-rules">Same device · two players · 100-point mechanical budget each. Large hulls hit harder but cost more and need more clearance. Both players can use touch controls.</p>`;
  window.addEventListener("message",event=>{if(event.origin!==location.origin)return;const index=this.frames.findIndex(f=>f.contentWindow===event.source);if(index<0)return;if(event.data?.type==="demo-key"){this.routeKey(String(event.data.key),Boolean(event.data.down));return;}if(event.data?.type!=="demo-state"||event.data.course!==this.challenge||event.data.round!==this.round)return;this.states[index]=event.data;this.update();});
  this.root.querySelector("#duelStart")!.addEventListener("click",()=>{if(!this.states.every(s=>s&&!s.garage))return;this.round++;this.states=this.states.map(s=>s?{...s,targets:0,completed:false,time:demolitionChallenge(this.challenge).time}:null);this.running=true;delete this.root.dataset.winner;this.text("duelStatus","GO! Same playground. Make the better mess.");this.frames.forEach(f=>f.contentWindow?.postMessage({type:"demo-start",round:this.round},location.origin));this.update();});
  this.root.querySelector("#duelChallenge")!.addEventListener("change",e=>{this.challenge=Number((e.target as HTMLSelectElement).value);this.load();});
  const key=(event:KeyboardEvent,down:boolean)=>{if(!this.running||/INPUT|SELECT/.test((event.target as HTMLElement).tagName))return;if(event.repeat&&[" ","w","ArrowUp","/"].includes(event.key))return;if(this.routeKey(event.key,down))event.preventDefault();};
  window.addEventListener("keydown",e=>key(e,true));window.addEventListener("keyup",e=>key(e,false));window.addEventListener("blur",()=>{for(const f of this.frames)for(const key of ["left","right","hammer","boost"])f.contentWindow?.postMessage({type:"demo-input",key,down:false},location.origin);});this.load();
 }
 private routeKey(key:string,down:boolean){if(!this.running)return false;const map:Record<string,[number,string]>={a:[0,"left"],d:[0,"right"]," ":[0,"hop"],j:[0,"hammer"],Shift:[0,"boost"],w:[0,"water"],ArrowLeft:[1,"left"],ArrowRight:[1,"right"],ArrowUp:[1,"hop"],Enter:[1,"hammer"],ArrowDown:[1,"boost"],"/":[1,"water"]};const action=map[key];if(!action)return false;this.frames[action[0]]?.contentWindow?.postMessage({type:"demo-input",key:action[1],down},location.origin);return true;}
 private load(){this.round=0;this.running=false;this.states=[null,null];this.frames=[];this.text("duelStatus","Build separately, then start together.");for(let i=0;i<2;i++){const frame=document.createElement("iframe");frame.title=i===0?"Teal demolition playground":"Coral demolition playground";frame.src=`/?lane=${i+1}&challenge=${this.challenge}`;this.root.querySelector(`#duelLane${i+1}`)!.replaceChildren(frame);this.frames.push(frame);}this.update();}
 private text(id:string,value:string){const el=this.root.querySelector(`#${id}`)!;if(el.textContent!==value)el.textContent=value;}
 private update(){
  const start=this.root.querySelector<HTMLButtonElement>("#duelStart")!;start.disabled=this.running||!this.states.every(s=>s&&!s.garage);start.textContent=this.running?"Race in progress":this.states.every(Boolean)?"Start / rematch →":"Loading machines…";
  this.states.forEach((s,i)=>this.text(i===0?"duelBlue":"duelRed",`${i===0?"TEAL":"CORAL"} · ${s?`${s.targets}/${s.goal} targets${s.garage?' · drawing…':''}`:"building…"}`));
  if(!this.running)return;const winners=this.states.map((s,i)=>s&&s.targets>=s.goal?i:-1).filter(i=>i>=0);const timedOut=this.states.every(s=>s&&s.time<=0);
  if(winners.length||timedOut){this.running=false;this.frames.forEach(f=>f.contentWindow?.postMessage({type:"demo-stop"},location.origin));const a=this.states[0]?.targets??0,b=this.states[1]?.targets??0;const winner=winners.length===1?winners[0]:a===b?-1:a>b?0:1;this.text("duelStatus",winner===-1?"A beautiful draw. Rematch?":`${winner===0?"TEAL":"CORAL"} wins! Rebuild, then rematch.`);this.root.dataset.winner=String(winner);start.disabled=false;start.textContent="Rebuild / rematch →";}
 }
}
