// Full UI review supplements the canvas action runner.
import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const out = 'artifacts/battle-club';
await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: process.env.LOBBERS_BROWSER_PATH });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:5183', { waitUntil: 'domcontentloaded' });
await page.locator('#botButton').waitFor();
await page.screenshot({ path: `${out}/menu.png` });
await page.locator('#menuHelpButton').click();
await page.screenshot({ path: `${out}/help.png` });
await page.keyboard.press('Escape');
await page.locator('#botButton').click();
await page.locator('#readyButton:not(:disabled)').waitFor();
await page.screenshot({ path: `${out}/ready.png` });
await page.locator('#readyButton').click();
await page.setViewportSize({ width: 1280, height: 720 });
await page.waitForFunction(() => document.querySelector('#hud-root')?.dataset.roundState === 'active');
await page.waitForTimeout(500);
await page.keyboard.down('d');
await page.waitForTimeout(350);
await page.keyboard.up('d');
await page.keyboard.press('Space');
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/move.png` });
await page.waitForFunction(() => {
  const h = document.querySelector('#hud-root');
  return h?.dataset.localTurn === 'true' && h.dataset.turnPhase === 'fire';
});
await page.mouse.move(980, 280);
await page.mouse.down();
await page.waitForTimeout(1000);
await page.screenshot({ path: `${out}/charge.png` });
await page.mouse.up();
await page.waitForTimeout(1200);
await page.screenshot({ path: `${out}/lob.png` });
await fs.writeFile(`${out}/state.json`, await page.evaluate(() => window.render_game_to_text()));
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/mobile-game.png` });
await page.locator('#leaveButton').click();
await page.locator('#lobbyPanel').waitFor();
await page.locator('#lobbyPanel').evaluate(e => e.scrollTop = 0);
await page.screenshot({ path: `${out}/mobile-menu.png` });
// Verify recap transitions against a separate HUD driven by controlled snapshots.
// Screenshots above are always from the real, server-driven match.
const recap = await page.evaluate(async () => {
  const { Hud } = await import('/src/ui/Hud.ts');
  const { EMPTY_SNAPSHOT } = await import('/src/game/viewModel.ts');
  const root = document.createElement('div');
  const hud = new Hud(root);
  const counts = { javelin: -1, shotput: -1, splitter: -1, discus: 0, mortar: 0, needle: 0, cluster: 0, anvil: 0 };
  const player = (side) => ({ sessionId: side, side, laneIndex: 0, name: side, hp: 100, x: 200, y: 1200, shieldHp: 0, shieldMaxHp: 50, grounded: true, charging: false, selectedAmmo: 'javelin', ammoCounts: counts, dashCooldownRemainingMs: 0, dashCooldownMs: 1050, pickupSeq: 0, lastThrowDistance: 0, bestThrowDistance: 999, throwSeq: 0, ready: true });
  const blue = player('blue'), red = player('red');
  const snapshot = { ...EMPTY_SNAPSHOT, players: [blue, red], roundState: 'countdown', currentTurnSessionId: 'blue' };
  const context = { connected: true, connecting: false, localSessionId: 'blue', status: 'Ready', selectedAmmo: 'javelin', chargeRatio: 0, cameraMode: 'follow', cameraZoom: 1, currentTurnSessionId: 'blue', turnPhase: 'resolving', turnRemainingMs: 4000, lobbies: [] };
  const read = () => ['recapDamage', 'recapShots', 'recapBest'].map(id => root.querySelector(`#${id}`).textContent);
  hud.render(snapshot, context);
  snapshot.roundState = 'active'; blue.throwSeq = 1; blue.lastThrowDistance = 80; red.hp = 70;
  hud.render(snapshot, context);
  const hit = read();
  red.throwSeq = 1; red.hp = 60;
  hud.render(snapshot, { ...context, currentTurnSessionId: 'red' });
  const rivalSelfDamage = read();
  blue.throwSeq = 2; blue.lastThrowDistance = 100; red.hp = 0; snapshot.roundState = 'ended'; snapshot.winnerSide = 'blue';
  hud.render(snapshot, { ...context, currentTurnSessionId: '' });
  const finalHit = read();
  snapshot.roundState = 'countdown'; red.hp = 100; blue.lastThrowDistance = 0;
  hud.render(snapshot, context);
  const rematch = read();
  return { hit, rivalSelfDamage, finalHit, rematch };
});
assert.deepEqual(recap.hit, ['30', '1', '80.0 m']);
assert.deepEqual(recap.rivalSelfDamage, recap.hit);
assert.deepEqual(recap.finalHit, ['90', '2', '100.0 m']);
assert.deepEqual(recap.rematch, ['0', '0', '0.0 m']);
await fs.writeFile(`${out}/errors.json`, JSON.stringify(errors));
assert.deepEqual(errors, []);
console.log(JSON.stringify({ screenshots: out, errors, recap }));
await browser.close();
